version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./desplegament:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_net

  app:
    build:
      context: ./desplegament
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./desplegament:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: vyneat
      DB_USERNAME: root
      DB_PASSWORD: mysql
    networks:
      - app_net

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "5432:3306"
    environment:
      MYSQL_DATABASE: vyneat
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net: