name: FTP Deploy Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build Laravel & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP with Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, gd, pdo, pdo_mysql
        tools: composer

    - name: Copy .env (opcional si no está en repo)
      run: |
        if [ ! -f .env ]; then
          echo "APP_NAME=Laravel" > .env
          echo "APP_KEY=" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "LOG_CHANNEL=stack" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          # Puedes añadir más variables aquí
        fi

    - name: Install dependencies (composer install)
      run: composer install --no-dev --optimize-autoloader

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        server-dir: /radiantarena.jeancarlos123.me/htdocs/
        dangerously-ignore-gitignore: true

